config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/listen'

  get 'article/create'
  get 'home/contact'

  root 'home#index'

  get 'home/index'

  get 'home/email'

  post '/create_email', to: 'application#create_email', as: :create_email

  get 'article/:id', to: 'home#show', as: :show_page

  get 'home/search/:tag', to: 'home#search', as: :search

  resources :articles
  resources :users

  get '/patreon' => redirect('https://www.patreon.com/bePatron?u=6850862'), as: :patreon

  # TheComments routes
  # TheComments routes
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns: %i[user_comments admin_comments]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :default_values

  def index
    @social = { "twitter": 'Tweet', "facebook": 'Share', "mail": 'E-mail' }
    @mast_head = Article.published.friendly.first(3)
    @is_root = true
  end

  def show
    @article = Article.published.friendly.find(params[:id])
    @comments = @article.comments.with_state(%i[draft published])
  end

  def search
    @tag = params[:tag]
    @articles = Article.tagged_with(@tag)
  end

  def listen
    @show_masthead = false
  end

  def default_values
    @read_more = false
    @is_root = false
    @read_more = true if action_name == 'index'
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def read_more?(article, read_more)
    if read_more == false
      article.content.html_safe
    else
      truncate(ActionView::Base.full_sanitizer.sanitize(article.content.html_safe), length: 300)
    end
  end
end

app/views/home/_article.html.erb
<!--

  <div class="ui horizontal divider">
    Share
  </div>

  <div class="ui center aligned spaced horizontal segments">

<a href="https://www.facebook.com/psychowarfare" class="ui blue inverted segment"><i class="facebook large icon"></i> Share</a>
<a class="ui teal inverted segment" href="https://twitter.com/intent/tweet?text=Hello%20world"> <i class="twitter large icon"></i>Tweet</a>
<a href="mailto:name@email.com" class="ui black inverted segment"><i class="mail large  icon"></i>Email</a>



    </div>
-->


<div class="ui item">
    <%= link_to(image_tag("#{article.header_image}",  class: "ui centered big segment article_image rounded image"), show_page_path(article)) %>

    <div class="ui center aligned text container">
      <h1 class="ui header ">
        <%= article.title %>
      </h1>

      <div class="sub header">
        <a class="ui blue label">
          <%= article.published_date %>
        </a>
      </div>
    </div>

    <% if article.media == "podcast" || article.media.nil? %>
      <div class="ui segment">
        <% if article.embedded_link != "" %>
          <iframe width="100%" height="166" scrolling="no" frameborder="no" src="<%= article.embedded_link %>&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
        <% end %>
      </div>
    <% end %>

  <div class="ui float right content">

    <h1 class="ui header left aligned">
    </h1>


      
    <%= read_more?(article, @read_more) %>


  </div>

</div>


 <% if article.useful_links.count > 0 %>
     <div class="ui horizontal divider">
        Useful links
     </div>

     <ul class="">
       <% article.useful_links.each do |key, value| %>
        <li>
           <%= link_to "#{key}", value, target: :blank, class: "ui teal tag label" %>
        </li>
      <% end %>
    </ul>
<% end %>

      <% article.timestamp.each do |item| %>
          <%= item %>
      <% end %>

 <% if article.people_mentioned.count > 0 %>
      <div class="ui horizontal divider">
          People Mentioned
      </div>
      <ul class="">
        <% article.people_mentioned.each do |key, value| %>
          <li>
            <%= link_to "#{key}", value, target: :blank, class: "ui blue tag label" %>
          </li>
        <% end %>
      </ul>
  <% end %>

app/views/home/_card.html.erb
<div class="card home_index_image">
  <div class="ui fluid image">
    <% if article.media != "podcast" && !article.media.nil? %>
      <div class="ui blue right ribbon label">
        <i class="comment icon"></i> <%= article.media %>
      </div>
    <% end %>
  <%= link_to(show_page_path(article), class: "image home_index_image") do %>
    <%= image_tag article.header_image %>
  </div>
      <div class="archive-home__content">
         <h3> <%= article.title %> </h3>
         <h5> <%= article.published_date %> </h5>
      </div>
  <% end %>
</div>

app/views/home/_emailModal.html.erb
<div class="ui basic modal">
  <div class="ui icon header">
    <i class="mail icon"></i>
    Get Updates From Us! Articles & Videos - No spam I promise :)
  </div>
  <div class="ui massive icon input header">
<%= form_for User.new(), url: { controller: "application" ,action: "create_email" }, html: {class: ""}, remote: true do |f| %>

<%= text_field(:user, :name, id: "name_input", class: "input", placeholder: "Your Name...") %>

<%= text_field(:user, :email, id: "email_input", class: "input", placeholder: "Your Email...") %>
</div>

  <div class="actions">
    <div class="ui red basic deny inverted button">
      <i class="remove icon"></i>
      No
    </div>

      <%= button_tag type: "submit", class: "ui green approve inverted button" do %>
       <i class="checkmark icon"></i>
        Yes
    <% end %>
<% end %>

    </div>
  </div>
</div>

app/views/home/_footer.html.erb
  <div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
      <div class="ui stackable inverted divided grid">
        <div class="5 wide centered column">
          <h4 class="ui inverted header">Copyright © 2018 Psycho Warfare</h4>
          <div class="ui inverted link list">
          <a class="item" onclick="showEmailModel();">Subscribe to our Email List</a>
          </div>
        </div>

      </div>
      <div class="ui inverted section divider"></div>
      <div class="ui horizontal inverted small divided link list">
   <!--     <a class="item" href="#">Terms and Conditions</a> -->
      </div>
    </div>
  </div>

app/views/home/_masthead.html.erb
<div class="ui centered grid vertical stripe inverted segment">
<div class="ui vertical stripe segment">
  <div class="ui text inverted container">
    <h1 class="ui orange header"> Welcome to the revolution</h1>
     <%= image_tag "newLogo2.png" , class: "ui medium left floated circular image" %>
    <p class="ui orange header"> To change our lives, we must first change our minds. </p>
    <%= link_to(home_listen_path, target: :blank) do %>
           <div class="ui huge inverted orange button" id="listen_button">Listen To The Podcast
             <i class="right play icon"></i>
          </div>
        <% end %>
    </div>


  </div>
</div>


<div class="ui centered text container">
  <h1 class="ui horizontal header divider">
    Recent Content
  </h1>

</div>

<!-- Following Menu -->
<div class="ui centered grid vertical stripe segment">

  <div class="ui three stackable cards">
    <% @mast_head.each do |article| %>
      <%= render 'home/card', article: article %>
    <% end %>
  </div>

  <div class="ui text container" style="padding-top: 20px">
    <%= link_to(articles_path) do %>
    <div class="ui huge centered aligned circular orange button">
      <i class="podcast icon"></i>All Episodes
    </div>
    <% end %>
  </div>
</div>



<div class="ui centered grid vertical stripe inverted segment">
<div class="ui vertical stripe segment">
  <div class="ui text inverted container">
    <h1 class="ui orange header"> Become a Patron</h1>
    <p class="ui orange header"> While we live in capitalism, we need to participate in it.  If you can support me, I would greatly appreciate it.  If you can't, I would
    just love to have you listen. </p>
    <%= link_to(patreon_url, target: :blank) do %>
    <div class="ui huge circular orange inverted button">
      <i class="paypal icon"></i>Become a Patron
    </div>
        <% end %>
    </div>


  </div>
</div>


<div class="ui centered grid vertical stripe segment">
<div class="ui vertical stripe segment">
  <div class="ui text inverted container">
    <h1 class="ui header"> Watch all the episodes</h1>
    <p class="ui header"> Take a look at all the episodes </p>
    <%= link_to(articles_path, target: :blank) do %>
    <button class="massive ui circular orange button">
      All Episodes (<%= Article.count %>)
    </button>
    <% end %>
    </div>


  </div>
</div>

app/views/home/_messages.html.erb
<div class="ui floating message transition hidden">
  <i class="close icon"></i>
  <div class="header centered">

  </div>

</div>

app/views/home/_sidebar.html.erb
<div class="ui horizontal divider">
  Live Broadcasts
</div>

<div class="ui horizontal divider">
  Follow Us :)
</div>
<%= link_to "https://www.facebook.com/psychowarfare", target: :blank  do  %>
      <div class="ui circular facebook icon button">
        <i class="facebook icon"></i>
      </div>
   <% end %>

<%= link_to "https://twitter.com/PsychoWarfareHQ", target: :blank  do  %>
      <div class="ui circular twitter icon button">
        <i class="twitter icon"></i>
      </div>
   <% end %>

   <%= link_to "https://www.youtube.com/channel/UClZ0kWdkSUvTIgFvpmX7jDA/videos", target: :blank  do  %>
      <div class="ui circular youtube icon button">
        <i class="youtube icon"></i>
      </div>
   <% end %>




<div class="ui horizontal divider">
  Get Updates
</div>

  <div class="segments">
  <a class="ui fluid button blue" onclick="showEmailModel();">
    <i class="mail icon"></i> Subscribe to our Email List
  </a>
  </div>
<div class="ui horizontal divider">
  Listen
</div>


<div class="ui center aligned segments">
   <%= link_to home_listen_path, target: :blank  do  %>
      <div class="ui fluid button red ">
        <i class="video play icon"></i>Where can I listen ?
      </div>
   <% end %>

  <!--

   <%= link_to "#"  do  %>

  <div class="ui center aligned black  segment"><i class="bar chart icon"></i>Stitcher
  </div>
  <% end %>
   <%= link_to "#"  do  %>

  <div class="ui center aligned orange segment"><i class="unmute icon"> </i>Overcast
  </div>
  <% end %>

-->


</div>

<div class="ui horizontal divider">
  Support Us
</div>

 <%= link_to "https://www.patreon.com/bePatron?u=6850862", target: :blank  do  %>

  <div class="ui center aligned orange inverted segment"><i class="paypal icon"></i>Become a Patron
  </div>
<% end %>


<div class="ui horizontal divider">
  Popular Posts
</div>
<div class="ui cards">
  <% Article.limit(5).each do |t| %>
  <div class="black card">
   <%= link_to show_page_path(t) do %>
   <div class="content">
    <div class="header center aligned"><%= t.title %> </div>
  </div>
  <% end %>
</div>

<% end %>
</div>

app/views/home/_topBar.html.erb
 <div class="ui fixed hidden borderless inverted menu">

    <div class="ui container">
      <a class="item" onclick="toggleSideBar();" id="slider">
        <i class="sidebar icon"></i>
       </a>

    <%= link_to(root_path , class: "header item") do %>
        <%= image_tag("newLogo2.png", class: "logo") %> Psychological Warfare
    <% end %>

    <div class="ui simple dropdown item">
      <i class="podcast circular inverted large purple icon"></i>
      Subscribe For Free!
      <i class="dropdown icon"></i>
      <div class="menu">

      <div class="header">Platforms</div>
          <%= link_to "iTunes", "https://itunes.apple.com/us/podcast/psychological-warfare-with-a-j-norton/id1265694390?mt=2", class: "item" %>
          <%= link_to "Google Play", "https://play.google.com/music/m/I32iuki5prnjqqmcyjbnz2mitkq?t=Psychological_Warfare_with_AJ_Norton", target: :blank, class: "item" %>
          <%= link_to "Overcast", "https://overcast.fm/itunes1265694390/psychological-warfare-with-a-j-norton", target: :blank, class: "item" %>
          <%= link_to "Stitcher", "http://www.stitcher.com/s?fid=157669&refid=stpr", target: :blank, class: "item"  %>
          <%= link_to "Sound Cloud", "https://soundcloud.com/psychowarfare", target: :blank, class: "item" %>

      </div>
    </div>
    <%= link_to("Episodes", articles_path , class: "item") %>

      <%= link_to "https://twitter.com/PsychoWarfareHQ", target: :blank, class: "item"  do  %>
            <div class="ui circular twitter icon button">
              <i class="twitter icon"></i>
            </div>
         <% end %>

         <%= link_to "https://www.youtube.com/channel/UClZ0kWdkSUvTIgFvpmX7jDA/videos", target: :blank, class: "item"  do  %>
            <div class="ui circular youtube icon button">
              <i class="play icon"></i>
            </div>
         <% end %>

         <%= link_to "https://www.patreon.com/bePatron?u=6850862", target: :blank, class: "item"  do  %>

          <div class="ui circular orange inverted button">
            <i class="paypal icon"></i>Become a Patron
          </div>
        <% end %>
      <a onclick="showEmailModel();" class="ui right floated dropdown item" id="contactMe">
       <i class="large icons">
         <i class="alarm icon" id="emailModel"></i>
         <i class="inverted corner add circle red icon"></i>
       </i> Get Updates
      </a>
    </div>
  </div>


<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <%= link_to("Home", root_path , class: "item") %>
  <%= link_to("Episodes", articles_path , class: "item") %>
  <%= link_to("Listen", home_listen_path , class: "item") %>
  <%= link_to "https://twitter.com/PsychoWarfareHQ", target: :blank, class: "item"  do  %>
        <div class="ui circular twitter icon button">
          <i class="twitter icon"></i>
          Twitter
        </div>
     <% end %>

     <%= link_to "https://www.youtube.com/channel/UClZ0kWdkSUvTIgFvpmX7jDA/videos", target: :blank, class: "item"  do  %>
        <div class="ui circular youtube icon button">
          <i class="play icon"> </i>
          Youtube
        </div>
     <% end %>
  <%= link_to "https://www.patreon.com/bePatron?u=6850862", target: :blank, class: "item"  do  %>

   <div class="ui circular orange inverted button">
     <i class="paypal icon"></i>Become a Patron
   </div>
 <% end %>
 <a onclick="showEmailModel();" class="ui right floated dropdown item" id="contactMe">
  <i class="large icons">
    <i class="alarm icon" id="emailModel"></i>
    <i class="inverted corner add circle red icon"></i>
  </i> Get Updates
 </a>
  <a class="item">Subscribe For Free! <i class="dropdown icon"></i></a>

      <%= link_to "iTunes", "https://itunes.apple.com/us/podcast/psychological-warfare-with-a-j-norton/id1265694390?mt=2", class: "item" %>
      <%= link_to "Overcast", "https://overcast.fm/itunes1265694390/psychological-warfare-with-a-j-norton", target: :blank, class: "item" %>
      <%= link_to "Stitcher", "http://www.stitcher.com/s?fid=157669&refid=stpr", target: :blank, class: "item"  %>
      <%= link_to "Google Play", "https://play.google.com/music/m/I32iuki5prnjqqmcyjbnz2mitkq?t=Psychological_Warfare_with_AJ_Norton", target: :blank, class: "item" %>
      <%= link_to "Sound Cloud", "https://soundcloud.com/psychowarfare", target: :blank, class: "item" %>

</div>

app/views/home/create_email.js.erb
<% if @new_user.save %>
  showMessage("success");  
<% else %>
  showMessage("error");
<% end %>

app/views/home/email.html.erb
  <div class="ui raised segment">
      <a class="ui red ribbon label">Subscribe!</a>
      <span>Become apart of the family!</span>
      <ul>
      	<li>Up to date podcasts</li>
      	<li>Special Articles</li>
      	<li>Awesome Videos</li>
      	<li>and more I will figure out more later!</li>
      </ul>
      <p></p>

      <div class="fluid ui massive blue icon button" onclick="showEmailModel();">
        <i class="announcement icon"></i>
        Sign Up!
      </div>
     
    </div>

app/views/home/index.html.erb
<!--
<div class="overlay">
      <div class="ui labeled icon vertical menu">
        <% @social.each do |k, v| %>
          <a class="item"> <%= semantic_icon("#{k}") %>  <%= "#{v}" %></a>
        <% end %>
      </div>
    </div>


-->

app/views/home/listen.html.erb
<div class="ui horizontal divider">
  Pick Your Platform :)
</div>

<%= link_to "https://itunes.apple.com/us/podcast/psychological-warfare-with-a-j-norton/id1265694390?mt=2", target: :blank  do  %>
      <div class="fluid ui massive purple icon button">
        <i class="apple icon"></i>
        iTunes
      </div>
   <% end %>

   <div class="ui horizontal divider">
    Or
  </div>

<%= link_to "https://play.google.com/music/m/I32iuki5prnjqqmcyjbnz2mitkq?t=Psychological_Warfare_with_AJ_Norton", target: :blank  do %>
      <div class="fluid ui massive green icon button">
        <i class="google icon"></i>
        Android
        <i class="android icon"></i>
      </div>
   <% end %>
<div class="ui horizontal divider">
    Or
  </div>
   <%= link_to "https://soundcloud.com/psychowarfare", target: :blank  do  %>
      <div class="fluid ui massive orange icon button">
        <i class="soundcloud icon"></i>
        SoundCloud
      </div>
   <% end %>
   <div class="ui horizontal divider">
    Or
  </div>

   

     <%= link_to "http://tun.in/piDrH", target: :blank  do  %>
      <div class="fluid ui massive black icon button">
        <i class="text width icon"></i>
        tunein
      </div>
   <% end %>
   <div class="ui horizontal divider">
    Or
  </div>

   
        <%= link_to "https://overcast.fm/itunes1265694390/psychological-warfare-with-a-j-norton", target: :blank  do  %>
      <div class="fluid ui massive yellow icon button">
        <i class="sound icon"></i>
        Overcast
      </div>
   <% end %>

   <div class="ui horizontal divider">
    Or
  </div>

      <%= link_to "http://www.stitcher.com/s?fid=157669&refid=stpr", target: :blank  do  %>
      <div class="fluid ui massive inverted twitter icon button">
        <i class="signal icon"></i>
        Stitcher
      </div>
   <% end %>

   <div class="ui horizontal divider">
    Or
  </div>

<h3>
  Don't see your platform here ?  Email (aj@psychowarfare.com) or Tweet at me and let me know!
</h3>

app/views/home/search.html.erb
<a class="ui blue basic label">
  <%= @tag %>
</a>

<div class="ui horizontal divider">
    	Results
</div>

<div class="ui divided  items">


 <% @articles.each do |article| %>

  <%= link_to(show_page_path(article), class: "ui item")  do %>
    <div class="ui small image">
      <%= image_tag(article.header_image, size: "100x100", alt: article) %>
    </div>
    <div class="content">
      <div class="header">
        <%= article.title %>
      </div>
      <div class="ui clearing divider"></div>
      <div class="description">
        <p> <%= truncate(article.search_content,length: 200)  %> </p>
      </div>

    </div>
  <% end %>
<% end %>
</div>

app/views/home/show.html.erb
<%= render "article", article: @article %>


    <div class="ui stacked segments">
      <div class="ui inverted segment">
        <h2 class="ui header">
            Recommended Posts:
       </h2> </div>
      <% if @article.recommended_articles.any? %>
        <% @article.recommended_articles.each do |r| %>
        <%= link_to show_page_path(r), target: :blank do %>
          <div class="ui blue inverted segment">
            <h3 class="ui header">
              <%= r.title %>
            </h3>
          </div>
          <% end %>
        <% end %>

      <% else %>
       <div class="ui red inverted segment">
            Check out more articles on the sidebar!
        </div>

      <% end %>

      </div>


  <h1>
  Leave a reply
  </h1>


<%= render partial: 'the_comments/tree', locals: { commentable: @article, comments_tree: @comments } %>